"""
Generate a SQL migration that creates storefront `products` rows from the
POS `stock_items` (grouped by name + category, sizes/colors become variants),
and links each stock_items.product_id back to the product it belongs to.

Intentionally leaves `image_url` null — photos are added by hand later via
/admin/products in the dashboard, per the shop owner's request.

Read-only against the source data (src/data/shop-seed.json, the same JSON the
POS seed migration was generated from). Writes only a new .sql file — never
touches Supabase directly. Run the generated file in the Supabase SQL editor.
"""
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SEED_JSON = ROOT / "src" / "data" / "shop-seed.json"
OUT_SQL = ROOT / "supabase" / "migrations" / "20260906120000_products_from_stock.sql"

CATEGORY_TO_TYPE = {
    "Bra & Lingerie": "Lingerie",
    "Underwear": "Underwear",
    "Jeans": "Bottoms",
    "Other": "Apparel",
}


def sql_str(value: str) -> str:
    return "'" + str(value).replace("'", "''") + "'"


def handle_for(name: str, category: str) -> str:
    base = f"{name}-{category}".lower()
    base = re.sub(r"[^a-z0-9]+", "-", base).strip("-")
    return base[:80]


def main() -> None:
    data = json.loads(SEED_JSON.read_text())
    stock = data["stockItems"]

    groups: dict[tuple[str, str], list[dict]] = defaultdict(list)
    for item in stock:
        groups[(item["name"], item["category"])].append(item)

    lines: list[str] = [
        "-- Generated by tools/products_from_stock.py — do not edit by hand.",
        "-- Creates one storefront `products` row per distinct (name, category) group",
        "-- in `stock_items`, with sizes/colors folded into the `variants` jsonb column,",
        "-- and links stock_items.product_id back to the product it belongs to.",
        "--",
        "-- Safe to re-run: matches existing products by `handle` and updates in place",
        "-- instead of duplicating. Does not touch or delete any existing product rows",
        "-- (e.g. unrelated products already in the table are left alone).",
        "begin;",
        "",
    ]

    for (name, category), rows in sorted(groups.items()):
        handle = handle_for(name, category)
        price = min(r["price"] for r in rows)
        product_type = CATEGORY_TO_TYPE.get(category, category)
        description = f"{name} — {category}. Available in {len(rows)} size/color combinations."

        variants = []
        for r in rows:
            title_parts = [p for p in [r.get("size"), r.get("color")] if p]
            variants.append(
                {
                    "id": r["sku"],
                    "title": " / ".join(title_parts) or "Default",
                    "price": r["price"],
                    "availableForSale": (r["stockIn"] - r["sold"]) > 0,
                    "selectedOptions": [
                        opt
                        for opt in [
                            {"name": "Size", "value": r["size"]} if r.get("size") else None,
                            {"name": "Color", "value": r["color"]} if r.get("color") else None,
                        ]
                        if opt
                    ],
                }
            )

        variants_json = json.dumps(variants)
        collections = ["Women"]
        if category == "Bra & Lingerie":
            collections.append("Lingerie")
        collections_sql = "ARRAY[" + ",".join(sql_str(c) for c in collections) + "]::text[]"

        lines += [
            f"-- {name} ({category}) — {len(rows)} SKU(s)",
            "insert into public.products (handle, title, description, product_type, price, currency, image_url, in_stock, collections, variants)",
            "values (",
            f"  {sql_str(handle)},",
            f"  {sql_str(name)},",
            f"  {sql_str(description)},",
            f"  {sql_str(product_type)},",
            f"  {price},",
            "  'USD',",
            "  null,",
            f"  {'true' if any((r['stockIn'] - r['sold']) > 0 for r in rows) else 'false'},",
            f"  {collections_sql},",
            f"  {sql_str(variants_json)}::jsonb",
            ")",
            "on conflict (handle) do update set",
            "  title = excluded.title,",
            "  description = excluded.description,",
            "  product_type = excluded.product_type,",
            "  price = excluded.price,",
            "  image_url = null,",
            "  in_stock = excluded.in_stock,",
            "  collections = excluded.collections,",
            "  variants = excluded.variants;",
            "",
            "update public.stock_items",
            "set product_id = (select id from public.products where handle = " + sql_str(handle) + ")",
            f"where name = {sql_str(name)} and category = {sql_str(category)};",
            "",
        ]

    lines += ["commit;", "", "notify pgrst, 'reload schema';", ""]

    OUT_SQL.write_text("\n".join(lines))
    print(f"→ {OUT_SQL.relative_to(ROOT)}")
    print(f"products to create/update: {len(groups)}")
    print(f"stock_items to link: {len(stock)}")


if __name__ == "__main__":
    sys.exit(main())
