-- Generated by tools/products_from_stock.py — do not edit by hand.
-- Creates one storefront `products` row per distinct (name, category) group
-- in `stock_items`, with sizes/colors folded into the `variants` jsonb column,
-- and links stock_items.product_id back to the product it belongs to.
--
-- Safe to re-run: matches existing products by `handle` and updates in place
-- instead of duplicating. Does not touch or delete any existing product rows
-- (e.g. unrelated products already in the table are left alone).
begin;

-- American-Style Thin (Other) — 2 SKU(s)
insert into public.products (handle, title, description, product_type, price, currency, image_url, in_stock, collections, variants)
values (
  'american-style-thin-other',
  'American-Style Thin',
  'American-Style Thin — Other. Available in 2 size/color combinations.',
  'Apparel',
  4.0,
  'USD',
  null,
  true,
  ARRAY['Women']::text[],
  '[{"id": "SKU001", "title": "M / Black", "price": 4.0, "availableForSale": true, "selectedOptions": [{"name": "Size", "value": "M"}, {"name": "Color", "value": "Black"}]}, {"id": "SKU002", "title": "M / White", "price": 4.0, "availableForSale": true, "selectedOptions": [{"name": "Size", "value": "M"}, {"name": "Color", "value": "White"}]}]'::jsonb
)
on conflict (handle) do update set
  title = excluded.title,
  description = excluded.description,
  product_type = excluded.product_type,
  price = excluded.price,
  image_url = null,
  in_stock = excluded.in_stock,
  collections = excluded.collections,
  variants = excluded.variants;

update public.stock_items
set product_id = (select id from public.products where handle = 'american-style-thin-other')
where name = 'American-Style Thin' and category = 'Other';

-- Black French lace sexy (Bra & Lingerie) — 3 SKU(s)
insert into public.products (handle, title, description, product_type, price, currency, image_url, in_stock, collections, variants)
values (
  'black-french-lace-sexy-bra-lingerie',
  'Black French lace sexy',
  'Black French lace sexy — Bra & Lingerie. Available in 3 size/color combinations.',
  'Lingerie',
  5.0,
  'USD',
  null,
  true,
  ARRAY['Women','Lingerie']::text[],
  '[{"id": "SKU005", "title": "32 / Black", "price": 5.0, "availableForSale": true, "selectedOptions": [{"name": "Size", "value": "32"}, {"name": "Color", "value": "Black"}]}, {"id": "SKU006", "title": "34 / Black", "price": 5.0, "availableForSale": true, "selectedOptions": [{"name": "Size", "value": "34"}, {"name": "Color", "value": "Black"}]}, {"id": "SKU007", "title": "36 / Black", "price": 5.0, "availableForSale": true, "selectedOptions": [{"name": "Size", "value": "36"}, {"name": "Color", "value": "Black"}]}]'::jsonb
)
on conflict (handle) do update set
  title = excluded.title,
  description = excluded.description,
  product_type = excluded.product_type,
  price = excluded.price,
  image_url = null,
  in_stock = excluded.in_stock,
  collections = excluded.collections,
  variants = excluded.variants;

update public.stock_items
set product_id = (select id from public.products where handle = 'black-french-lace-sexy-bra-lingerie')
where name = 'Black French lace sexy' and category = 'Bra & Lingerie';

-- Blue tiffiny top bow (Tops) — 1 SKU(s)
insert into public.products (handle, title, description, product_type, price, currency, image_url, in_stock, collections, variants)
values (
  'blue-tiffiny-top-bow-tops',
  'Blue tiffiny top bow',
  'Blue tiffiny top bow — Tops. Available in 1 size/color combinations.',
  'Tops',
  4.0,
  'USD',
  null,
  false,
  ARRAY['Women']::text[],
  '[{"id": "SKU039", "title": "Free size / Blue", "price": 4.0, "availableForSale": false, "selectedOptions": [{"name": "Size", "value": "Free size"}, {"name": "Color", "value": "Blue"}]}]'::jsonb
)
on conflict (handle) do update set
  title = excluded.title,
  description = excluded.description,
  product_type = excluded.product_type,
  price = excluded.price,
  image_url = null,
  in_stock = excluded.in_stock,
  collections = excluded.collections,
  variants = excluded.variants;

update public.stock_items
set product_id = (select id from public.products where handle = 'blue-tiffiny-top-bow-tops')
where name = 'Blue tiffiny top bow' and category = 'Tops';

-- Bra sbai (Bra & Lingerie) — 3 SKU(s)
insert into public.products (handle, title, description, product_type, price, currency, image_url, in_stock, collections, variants)
values (
  'bra-sbai-bra-lingerie',
  'Bra sbai',
  'Bra sbai — Bra & Lingerie. Available in 3 size/color combinations.',
  'Lingerie',
  5.5,
  'USD',
  null,
  true,
  ARRAY['Women','Lingerie']::text[],
  '[{"id": "SKU020", "title": "32 / Black", "price": 5.5, "availableForSale": true, "selectedOptions": [{"name": "Size", "value": "32"}, {"name": "Color", "value": "Black"}]}, {"id": "SKU021", "title": "32 / White", "price": 5.5, "availableForSale": true, "selectedOptions": [{"name": "Size", "value": "32"}, {"name": "Color", "value": "White"}]}, {"id": "SKU022", "title": "34 / Black", "price": 5.5, "availableForSale": true, "selectedOptions": [{"name": "Size", "value": "34"}, {"name": "Color", "value": "Black"}]}]'::jsonb
)
on conflict (handle) do update set
  title = excluded.title,
  description = excluded.description,
  product_type = excluded.product_type,
  price = excluded.price,
  image_url = null,
  in_stock = excluded.in_stock,
  collections = excluded.collections,
  variants = excluded.variants;

update public.stock_items
set product_id = (select id from public.products where handle = 'bra-sbai-bra-lingerie')
where name = 'Bra sbai' and category = 'Bra & Lingerie';

-- French-Style Lace Lingerie (Bra & Lingerie) — 5 SKU(s)
insert into public.products (handle, title, description, product_type, price, currency, image_url, in_stock, collections, variants)
values (
  'french-style-lace-lingerie-bra-lingerie',
  'French-Style Lace Lingerie',
  'French-Style Lace Lingerie — Bra & Lingerie. Available in 5 size/color combinations.',
  'Lingerie',
  5.5,
  'USD',
  null,
  true,
  ARRAY['Women','Lingerie']::text[],
  '[{"id": "SKU003", "title": "32 / Black", "price": 5.5, "availableForSale": true, "selectedOptions": [{"name": "Size", "value": "32"}, {"name": "Color", "value": "Black"}]}, {"id": "SKU004", "title": "34 / Black", "price": 5.5, "availableForSale": false, "selectedOptions": [{"name": "Size", "value": "34"}, {"name": "Color", "value": "Black"}]}, {"id": "SKU032", "title": "32 / Black", "price": 5.5, "availableForSale": true, "selectedOptions": [{"name": "Size", "value": "32"}, {"name": "Color", "value": "Black"}]}, {"id": "SKU033", "title": "34 / Black", "price": 5.5, "availableForSale": true, "selectedOptions": [{"name": "Size", "value": "34"}, {"name": "Color", "value": "Black"}]}, {"id": "SKU034", "title": "36 / Black", "price": 5.5, "availableForSale": false, "selectedOptions": [{"name": "Size", "value": "36"}, {"name": "Color", "value": "Black"}]}]'::jsonb
)
on conflict (handle) do update set
  title = excluded.title,
  description = excluded.description,
  product_type = excluded.product_type,
  price = excluded.price,
  image_url = null,
  in_stock = excluded.in_stock,
  collections = excluded.collections,
  variants = excluded.variants;

update public.stock_items
set product_id = (select id from public.products where handle = 'french-style-lace-lingerie-bra-lingerie')
where name = 'French-Style Lace Lingerie' and category = 'Bra & Lingerie';

-- French-Style Sexy Lace (Bra & Lingerie) — 2 SKU(s)
insert into public.products (handle, title, description, product_type, price, currency, image_url, in_stock, collections, variants)
values (
  'french-style-sexy-lace-bra-lingerie',
  'French-Style Sexy Lace',
  'French-Style Sexy Lace — Bra & Lingerie. Available in 2 size/color combinations.',
  'Lingerie',
  5.5,
  'USD',
  null,
  true,
  ARRAY['Women','Lingerie']::text[],
  '[{"id": "SKU009", "title": "32 / Black", "price": 5.5, "availableForSale": true, "selectedOptions": [{"name": "Size", "value": "32"}, {"name": "Color", "value": "Black"}]}, {"id": "SKU010", "title": "34 / Black", "price": 5.5, "availableForSale": true, "selectedOptions": [{"name": "Size", "value": "34"}, {"name": "Color", "value": "Black"}]}]'::jsonb
)
on conflict (handle) do update set
  title = excluded.title,
  description = excluded.description,
  product_type = excluded.product_type,
  price = excluded.price,
  image_url = null,
  in_stock = excluded.in_stock,
  collections = excluded.collections,
  variants = excluded.variants;

update public.stock_items
set product_id = (select id from public.products where handle = 'french-style-sexy-lace-bra-lingerie')
where name = 'French-Style Sexy Lace' and category = 'Bra & Lingerie';

-- Pure Desir Bra (Bra & Lingerie) — 1 SKU(s)
insert into public.products (handle, title, description, product_type, price, currency, image_url, in_stock, collections, variants)
values (
  'pure-desir-bra-bra-lingerie',
  'Pure Desir Bra',
  'Pure Desir Bra — Bra & Lingerie. Available in 1 size/color combinations.',
  'Lingerie',
  5.5,
  'USD',
  null,
  false,
  ARRAY['Women','Lingerie']::text[],
  '[{"id": "SKU030", "title": "34 / Black", "price": 5.5, "availableForSale": false, "selectedOptions": [{"name": "Size", "value": "34"}, {"name": "Color", "value": "Black"}]}]'::jsonb
)
on conflict (handle) do update set
  title = excluded.title,
  description = excluded.description,
  product_type = excluded.product_type,
  price = excluded.price,
  image_url = null,
  in_stock = excluded.in_stock,
  collections = excluded.collections,
  variants = excluded.variants;

update public.stock_items
set product_id = (select id from public.products where handle = 'pure-desir-bra-bra-lingerie')
where name = 'Pure Desir Bra' and category = 'Bra & Lingerie';

-- Satin Lace (Bra & Lingerie) — 1 SKU(s)
insert into public.products (handle, title, description, product_type, price, currency, image_url, in_stock, collections, variants)
values (
  'satin-lace-bra-lingerie',
  'Satin Lace',
  'Satin Lace — Bra & Lingerie. Available in 1 size/color combinations.',
  'Lingerie',
  5.5,
  'USD',
  null,
  true,
  ARRAY['Women','Lingerie']::text[],
  '[{"id": "SKU008", "title": "M / Black", "price": 5.5, "availableForSale": true, "selectedOptions": [{"name": "Size", "value": "M"}, {"name": "Color", "value": "Black"}]}]'::jsonb
)
on conflict (handle) do update set
  title = excluded.title,
  description = excluded.description,
  product_type = excluded.product_type,
  price = excluded.price,
  image_url = null,
  in_stock = excluded.in_stock,
  collections = excluded.collections,
  variants = excluded.variants;

update public.stock_items
set product_id = (select id from public.products where handle = 'satin-lace-bra-lingerie')
where name = 'Satin Lace' and category = 'Bra & Lingerie';

-- Satin Lace ligerie (Bra & Lingerie) — 7 SKU(s)
insert into public.products (handle, title, description, product_type, price, currency, image_url, in_stock, collections, variants)
values (
  'satin-lace-ligerie-bra-lingerie',
  'Satin Lace ligerie',
  'Satin Lace ligerie — Bra & Lingerie. Available in 7 size/color combinations.',
  'Lingerie',
  5.5,
  'USD',
  null,
  true,
  ARRAY['Women','Lingerie']::text[],
  '[{"id": "SKU026", "title": "32 / Black", "price": 5.5, "availableForSale": true, "selectedOptions": [{"name": "Size", "value": "32"}, {"name": "Color", "value": "Black"}]}, {"id": "SKU027", "title": "32 / White", "price": 5.5, "availableForSale": true, "selectedOptions": [{"name": "Size", "value": "32"}, {"name": "Color", "value": "White"}]}, {"id": "SKU028", "title": "36 / Black", "price": 5.5, "availableForSale": true, "selectedOptions": [{"name": "Size", "value": "36"}, {"name": "Color", "value": "Black"}]}, {"id": "SKU029", "title": "34 / Black", "price": 5.5, "availableForSale": false, "selectedOptions": [{"name": "Size", "value": "34"}, {"name": "Color", "value": "Black"}]}, {"id": "SKU042", "title": "32 / Black", "price": 5.5, "availableForSale": true, "selectedOptions": [{"name": "Size", "value": "32"}, {"name": "Color", "value": "Black"}]}, {"id": "SKU043", "title": "34 / Black", "price": 5.5, "availableForSale": true, "selectedOptions": [{"name": "Size", "value": "34"}, {"name": "Color", "value": "Black"}]}, {"id": "SKU044", "title": "38 / Black", "price": 5.5, "availableForSale": false, "selectedOptions": [{"name": "Size", "value": "38"}, {"name": "Color", "value": "Black"}]}]'::jsonb
)
on conflict (handle) do update set
  title = excluded.title,
  description = excluded.description,
  product_type = excluded.product_type,
  price = excluded.price,
  image_url = null,
  in_stock = excluded.in_stock,
  collections = excluded.collections,
  variants = excluded.variants;

update public.stock_items
set product_id = (select id from public.products where handle = 'satin-lace-ligerie-bra-lingerie')
where name = 'Satin Lace ligerie' and category = 'Bra & Lingerie';

-- Short Jean (Jeans) — 3 SKU(s)
insert into public.products (handle, title, description, product_type, price, currency, image_url, in_stock, collections, variants)
values (
  'short-jean-jeans',
  'Short Jean',
  'Short Jean — Jeans. Available in 3 size/color combinations.',
  'Bottoms',
  4.0,
  'USD',
  null,
  true,
  ARRAY['Women']::text[],
  '[{"id": "SKU018", "title": "S / Dark blue", "price": 8.5, "availableForSale": true, "selectedOptions": [{"name": "Size", "value": "S"}, {"name": "Color", "value": "Dark blue"}]}, {"id": "SKU019", "title": "S / Light blue", "price": 8.5, "availableForSale": true, "selectedOptions": [{"name": "Size", "value": "S"}, {"name": "Color", "value": "Light blue"}]}, {"id": "SKU047", "title": "Free size / Black", "price": 4.0, "availableForSale": false, "selectedOptions": [{"name": "Size", "value": "Free size"}, {"name": "Color", "value": "Black"}]}]'::jsonb
)
on conflict (handle) do update set
  title = excluded.title,
  description = excluded.description,
  product_type = excluded.product_type,
  price = excluded.price,
  image_url = null,
  in_stock = excluded.in_stock,
  collections = excluded.collections,
  variants = excluded.variants;

update public.stock_items
set product_id = (select id from public.products where handle = 'short-jean-jeans')
where name = 'Short Jean' and category = 'Jeans';

-- Summer french satin (Bra & Lingerie) — 7 SKU(s)
insert into public.products (handle, title, description, product_type, price, currency, image_url, in_stock, collections, variants)
values (
  'summer-french-satin-bra-lingerie',
  'Summer french satin',
  'Summer french satin — Bra & Lingerie. Available in 7 size/color combinations.',
  'Lingerie',
  5.5,
  'USD',
  null,
  true,
  ARRAY['Women','Lingerie']::text[],
  '[{"id": "SKU011", "title": "32 / Black", "price": 5.5, "availableForSale": false, "selectedOptions": [{"name": "Size", "value": "32"}, {"name": "Color", "value": "Black"}]}, {"id": "SKU012", "title": "32 / White", "price": 5.5, "availableForSale": true, "selectedOptions": [{"name": "Size", "value": "32"}, {"name": "Color", "value": "White"}]}, {"id": "SKU013", "title": "34 / Black", "price": 5.5, "availableForSale": false, "selectedOptions": [{"name": "Size", "value": "34"}, {"name": "Color", "value": "Black"}]}, {"id": "SKU035", "title": "32 / Black", "price": 5.5, "availableForSale": true, "selectedOptions": [{"name": "Size", "value": "32"}, {"name": "Color", "value": "Black"}]}, {"id": "SKU036", "title": "34 / Black", "price": 5.5, "availableForSale": true, "selectedOptions": [{"name": "Size", "value": "34"}, {"name": "Color", "value": "Black"}]}, {"id": "SKU037", "title": "36 / Black", "price": 5.5, "availableForSale": true, "selectedOptions": [{"name": "Size", "value": "36"}, {"name": "Color", "value": "Black"}]}, {"id": "SKU038", "title": "32 / White", "price": 5.5, "availableForSale": true, "selectedOptions": [{"name": "Size", "value": "32"}, {"name": "Color", "value": "White"}]}]'::jsonb
)
on conflict (handle) do update set
  title = excluded.title,
  description = excluded.description,
  product_type = excluded.product_type,
  price = excluded.price,
  image_url = null,
  in_stock = excluded.in_stock,
  collections = excluded.collections,
  variants = excluded.variants;

update public.stock_items
set product_id = (select id from public.products where handle = 'summer-french-satin-bra-lingerie')
where name = 'Summer french satin' and category = 'Bra & Lingerie';

-- Tank Top (Tops) — 1 SKU(s)
insert into public.products (handle, title, description, product_type, price, currency, image_url, in_stock, collections, variants)
values (
  'tank-top-tops',
  'Tank Top',
  'Tank Top — Tops. Available in 1 size/color combinations.',
  'Tops',
  7.5,
  'USD',
  null,
  true,
  ARRAY['Women']::text[],
  '[{"id": "SKU025", "title": "S / Black", "price": 7.5, "availableForSale": true, "selectedOptions": [{"name": "Size", "value": "S"}, {"name": "Color", "value": "Black"}]}]'::jsonb
)
on conflict (handle) do update set
  title = excluded.title,
  description = excluded.description,
  product_type = excluded.product_type,
  price = excluded.price,
  image_url = null,
  in_stock = excluded.in_stock,
  collections = excluded.collections,
  variants = excluded.variants;

update public.stock_items
set product_id = (select id from public.products where handle = 'tank-top-tops')
where name = 'Tank Top' and category = 'Tops';

-- Underwear (Underwear) — 6 SKU(s)
insert into public.products (handle, title, description, product_type, price, currency, image_url, in_stock, collections, variants)
values (
  'underwear-underwear',
  'Underwear',
  'Underwear — Underwear. Available in 6 size/color combinations.',
  'Underwear',
  1.25,
  'USD',
  null,
  true,
  ARRAY['Women']::text[],
  '[{"id": "SKU014", "title": "S / Black", "price": 1.25, "availableForSale": true, "selectedOptions": [{"name": "Size", "value": "S"}, {"name": "Color", "value": "Black"}]}, {"id": "SKU015", "title": "S / White", "price": 1.25, "availableForSale": true, "selectedOptions": [{"name": "Size", "value": "S"}, {"name": "Color", "value": "White"}]}, {"id": "SKU016", "title": "M / Black", "price": 1.25, "availableForSale": true, "selectedOptions": [{"name": "Size", "value": "M"}, {"name": "Color", "value": "Black"}]}, {"id": "SKU017", "title": "M / White", "price": 1.25, "availableForSale": true, "selectedOptions": [{"name": "Size", "value": "M"}, {"name": "Color", "value": "White"}]}, {"id": "SKU040", "title": "M / Black", "price": 1.25, "availableForSale": true, "selectedOptions": [{"name": "Size", "value": "M"}, {"name": "Color", "value": "Black"}]}, {"id": "SKU041", "title": "M / White", "price": 1.25, "availableForSale": false, "selectedOptions": [{"name": "Size", "value": "M"}, {"name": "Color", "value": "White"}]}]'::jsonb
)
on conflict (handle) do update set
  title = excluded.title,
  description = excluded.description,
  product_type = excluded.product_type,
  price = excluded.price,
  image_url = null,
  in_stock = excluded.in_stock,
  collections = excluded.collections,
  variants = excluded.variants;

update public.stock_items
set product_id = (select id from public.products where handle = 'underwear-underwear')
where name = 'Underwear' and category = 'Underwear';

-- White tank top (Tops) — 1 SKU(s)
insert into public.products (handle, title, description, product_type, price, currency, image_url, in_stock, collections, variants)
values (
  'white-tank-top-tops',
  'White tank top',
  'White tank top — Tops. Available in 1 size/color combinations.',
  'Tops',
  3.0,
  'USD',
  null,
  true,
  ARRAY['Women']::text[],
  '[{"id": "SKU031", "title": "Free size / White", "price": 3.0, "availableForSale": true, "selectedOptions": [{"name": "Size", "value": "Free size"}, {"name": "Color", "value": "White"}]}]'::jsonb
)
on conflict (handle) do update set
  title = excluded.title,
  description = excluded.description,
  product_type = excluded.product_type,
  price = excluded.price,
  image_url = null,
  in_stock = excluded.in_stock,
  collections = excluded.collections,
  variants = excluded.variants;

update public.stock_items
set product_id = (select id from public.products where handle = 'white-tank-top-tops')
where name = 'White tank top' and category = 'Tops';

-- ZARA TOP (Tops) — 2 SKU(s)
insert into public.products (handle, title, description, product_type, price, currency, image_url, in_stock, collections, variants)
values (
  'zara-top-tops',
  'ZARA TOP',
  'ZARA TOP — Tops. Available in 2 size/color combinations.',
  'Tops',
  3.5,
  'USD',
  null,
  true,
  ARRAY['Women']::text[],
  '[{"id": "SKU023", "title": "M / White", "price": 3.5, "availableForSale": false, "selectedOptions": [{"name": "Size", "value": "M"}, {"name": "Color", "value": "White"}]}, {"id": "SKU024", "title": "M / Black", "price": 3.5, "availableForSale": true, "selectedOptions": [{"name": "Size", "value": "M"}, {"name": "Color", "value": "Black"}]}]'::jsonb
)
on conflict (handle) do update set
  title = excluded.title,
  description = excluded.description,
  product_type = excluded.product_type,
  price = excluded.price,
  image_url = null,
  in_stock = excluded.in_stock,
  collections = excluded.collections,
  variants = excluded.variants;

update public.stock_items
set product_id = (select id from public.products where handle = 'zara-top-tops')
where name = 'ZARA TOP' and category = 'Tops';

-- zara tank top (Tops) — 2 SKU(s)
insert into public.products (handle, title, description, product_type, price, currency, image_url, in_stock, collections, variants)
values (
  'zara-tank-top-tops',
  'zara tank top',
  'zara tank top — Tops. Available in 2 size/color combinations.',
  'Tops',
  3.5,
  'USD',
  null,
  false,
  ARRAY['Women']::text[],
  '[{"id": "SKU045", "title": "Free size / White", "price": 3.5, "availableForSale": false, "selectedOptions": [{"name": "Size", "value": "Free size"}, {"name": "Color", "value": "White"}]}, {"id": "SKU046", "title": "Free size / Blue", "price": 3.5, "availableForSale": false, "selectedOptions": [{"name": "Size", "value": "Free size"}, {"name": "Color", "value": "Blue"}]}]'::jsonb
)
on conflict (handle) do update set
  title = excluded.title,
  description = excluded.description,
  product_type = excluded.product_type,
  price = excluded.price,
  image_url = null,
  in_stock = excluded.in_stock,
  collections = excluded.collections,
  variants = excluded.variants;

update public.stock_items
set product_id = (select id from public.products where handle = 'zara-tank-top-tops')
where name = 'zara tank top' and category = 'Tops';

commit;

notify pgrst, 'reload schema';
