-- Generated by tools/import_excel.py — historical data from Clothing_Shop_Management3.xlsx.
-- Idempotent: safe to run more than once (natural keys sku / code are unique).

begin;

-- ── stock items ───────────────────────────────────────────────
insert into public.stock_items (sku, name, category, size, color, cost, price, stock_in, sold)
values
  ('SKU001', 'American-Style Thin', 'Other', 'M', 'Black', 0.96, 4.0, 3, 0),
  ('SKU002', 'American-Style Thin', 'Other', 'M', 'White', 0.96, 4.0, 3, 0),
  ('SKU003', 'French-Style Lace Lingerie', 'Bra & Lingerie', '32', 'Black', 1.84, 5.5, 2, 1),
  ('SKU004', 'French-Style Lace Lingerie', 'Bra & Lingerie', '34', 'Black', 1.84, 5.5, 2, 2),
  ('SKU005', 'Black French lace sexy', 'Bra & Lingerie', '32', 'Black', 1.84, 5.0, 2, 1),
  ('SKU006', 'Black French lace sexy', 'Bra & Lingerie', '34', 'Black', 1.84, 5.0, 1, 0),
  ('SKU007', 'Black French lace sexy', 'Bra & Lingerie', '36', 'Black', 1.84, 5.0, 1, 0),
  ('SKU008', 'Satin Lace', 'Bra & Lingerie', 'M', 'Black', 2.88, 5.5, 1, 0),
  ('SKU009', 'French-Style Sexy Lace', 'Bra & Lingerie', '32', 'Black', 2.19, 5.5, 3, 0),
  ('SKU010', 'French-Style Sexy Lace', 'Bra & Lingerie', '34', 'Black', 2.19, 5.5, 2, 0),
  ('SKU011', 'Summer french satin', 'Bra & Lingerie', '32', 'Black', 1.91, 5.5, 2, 2),
  ('SKU012', 'Summer french satin', 'Bra & Lingerie', '32', 'White', 1.91, 5.5, 1, 0),
  ('SKU013', 'Summer french satin', 'Bra & Lingerie', '34', 'Black', 1.91, 5.5, 1, 1),
  ('SKU014', 'Underwear', 'Underwear', 'S', 'Black', 0.42, 1.25, 3, 1),
  ('SKU015', 'Underwear', 'Underwear', 'S', 'White', 0.42, 1.25, 2, 1),
  ('SKU016', 'Underwear', 'Underwear', 'M', 'Black', 0.42, 1.25, 3, 0),
  ('SKU017', 'Underwear', 'Underwear', 'M', 'White', 0.42, 1.25, 2, 0),
  ('SKU018', 'Short Jean', 'Jeans', 'S', 'Dark blue', 5.76, 8.5, 1, 0),
  ('SKU019', 'Short Jean', 'Jeans', 'S', 'Light blue', 5.76, 8.5, 1, 0),
  ('SKU020', 'Bra sbai', 'Bra & Lingerie', '32', 'Black', 1.84, 5.5, 1, 0),
  ('SKU021', 'Bra sbai', 'Bra & Lingerie', '32', 'White', 1.84, 5.5, 1, 0),
  ('SKU022', 'Bra sbai', 'Bra & Lingerie', '34', 'Black', 1.84, 5.5, 1, 0),
  ('SKU023', 'ZARA TOP', 'Tops', 'M', 'White', 2.4, 3.5, 3, 4),
  ('SKU024', 'ZARA TOP', 'Tops', 'M', 'Black', 2.4, 3.5, 2, 0),
  ('SKU025', 'Tank Top', 'Tops', 'S', 'Black', 4.5, 7.5, 1, 0),
  ('SKU026', 'Satin Lace ligerie', 'Bra & Lingerie', '32', 'Black', 2.22, 5.5, 3, 2),
  ('SKU027', 'Satin Lace ligerie', 'Bra & Lingerie', '32', 'White', 2.22, 5.5, 1, 0),
  ('SKU028', 'Satin Lace ligerie', 'Bra & Lingerie', '36', 'Black', 2.22, 5.5, 1, 0),
  ('SKU029', 'Satin Lace ligerie', 'Bra & Lingerie', '34', 'Black', 2.22, 5.5, 3, 3),
  ('SKU030', 'Pure Desir Bra', 'Bra & Lingerie', '34', 'Black', 2.22, 5.5, 1, 1),
  ('SKU031', 'White tank top', 'Tops', 'Free size', 'White', 2.0, 3.0, 1, 0),
  ('SKU032', 'French-Style Lace Lingerie', 'Bra & Lingerie', '32', 'Black', 1.91, 5.5, 2, 1),
  ('SKU033', 'French-Style Lace Lingerie', 'Bra & Lingerie', '34', 'Black', 1.91, 5.5, 2, 0),
  ('SKU034', 'French-Style Lace Lingerie', 'Bra & Lingerie', '36', 'Black', 1.91, 5.5, 2, 2),
  ('SKU035', 'Summer french satin', 'Bra & Lingerie', '32', 'Black', 2.17, 5.5, 2, 0),
  ('SKU036', 'Summer french satin', 'Bra & Lingerie', '34', 'Black', 2.17, 5.5, 2, 0),
  ('SKU037', 'Summer french satin', 'Bra & Lingerie', '36', 'Black', 2.17, 5.5, 3, 1),
  ('SKU038', 'Summer french satin', 'Bra & Lingerie', '32', 'White', 2.17, 5.5, 1, 0),
  ('SKU039', 'Blue tiffiny top bow', 'Tops', 'Free size', 'Blue', 2.25, 4.0, 1, 1),
  ('SKU040', 'Underwear', 'Underwear', 'M', 'Black', 0.83, 1.25, 2, 1),
  ('SKU041', 'Underwear', 'Underwear', 'M', 'White', 0.83, 1.25, 1, 1),
  ('SKU042', 'Satin Lace ligerie', 'Bra & Lingerie', '32', 'Black', 2.0, 5.5, 2, 0),
  ('SKU043', 'Satin Lace ligerie', 'Bra & Lingerie', '34', 'Black', 2.0, 5.5, 2, 0),
  ('SKU044', 'Satin Lace ligerie', 'Bra & Lingerie', '38', 'Black', 2.0, 5.5, 1, 1),
  ('SKU045', 'zara tank top', 'Tops', 'Free size', 'White', 2.0, 3.5, 1, 1),
  ('SKU046', 'zara tank top', 'Tops', 'Free size', 'Blue', 2.0, 3.5, 1, 1),
  ('SKU047', 'Short Jean', 'Jeans', 'Free size', 'Black', 2.5, 4.0, 1, 1)
on conflict (sku) do update set
  name = excluded.name, category = excluded.category, size = excluded.size,
  color = excluded.color, cost = excluded.cost, price = excluded.price,
  stock_in = excluded.stock_in, sold = excluded.sold;

-- ── sales + line items ────────────────────────────────────────
with s as (
  insert into public.sales (code, sold_at, customer_name, phone, address, city, channel,
    delivery_method, delivery_fee, delivery_status, status, subtotal, total, paid, note)
  values ('S-0001', '2026-08-31', 'Noch Jasmine', '15848188', 'សម្ដេចមង្គអៀប 228', 'Phnom Penh', 'booking', 'Delivery', 1.5, 'delivered', 'confirmed', 14.5, 16.0, 16.0, null)
  on conflict (code) do update set customer_name = excluded.customer_name
  returning id
)
insert into public.sale_items (sale_id, stock_item_id, name, size, color, qty, unit_price, unit_cost)
select s.id, si.id, v.name, v.size, v.color, v.qty, v.unit_price, v.unit_cost
from s
cross join (values
  (null, 'Jean', 'M', '', 1, 9.0, 0.0),
  ('SKU032', 'French-Style Lace Lingerie', '32', 'Black', 1, 5.5, 1.91)
) as v(sku, name, size, color, qty, unit_price, unit_cost)
left join public.stock_items si on si.sku = v.sku
where not exists (select 1 from public.sale_items existing where existing.sale_id = s.id);

with s as (
  insert into public.sales (code, sold_at, customer_name, phone, address, city, channel,
    delivery_method, delivery_fee, delivery_status, status, subtotal, total, paid, note)
  values ('S-0002', '2026-03-09', 'Wang Ning', '7978293111', 'BTB ភ្នំសំពៅ (VET)', 'Btb', 'booking', 'Delivery', 2.0, 'delivered', 'confirmed', 11.0, 13.0, 13.0, null)
  on conflict (code) do update set customer_name = excluded.customer_name
  returning id
)
insert into public.sale_items (sale_id, stock_item_id, name, size, color, qty, unit_price, unit_cost)
select s.id, si.id, v.name, v.size, v.color, v.qty, v.unit_price, v.unit_cost
from s
cross join (values
  ('SKU033', 'French-Style Lace Lingerie', '34', 'Black', 2, 5.5, 1.91)
) as v(sku, name, size, color, qty, unit_price, unit_cost)
left join public.stock_items si on si.sku = v.sku
where not exists (select 1 from public.sale_items existing where existing.sale_id = s.id);

with s as (
  insert into public.sales (code, sold_at, customer_name, phone, address, city, channel,
    delivery_method, delivery_fee, delivery_status, status, subtotal, total, paid, note)
  values ('S-0003', '2026-03-09', 'J', '88916635', 'ARAKAWA ក្រោយពេទ្យរ៉ូយាល់', 'Phnom Penh', 'booking', 'Delivery', 1.5, 'preparing', 'confirmed', 16.5, 18.0, 9.0, null)
  on conflict (code) do update set customer_name = excluded.customer_name
  returning id
)
insert into public.sale_items (sale_id, stock_item_id, name, size, color, qty, unit_price, unit_cost)
select s.id, si.id, v.name, v.size, v.color, v.qty, v.unit_price, v.unit_cost
from s
cross join (values
  ('SKU032', 'French-Style Lace Lingerie', '32', 'Black', 1, 5.5, 1.91),
  ('SKU042', 'Satin Lace ligerie', '32', 'Black', 1, 5.5, 2.0),
  ('SKU030', 'Pure Desir Bra', '34', 'Black', 1, 5.5, 2.22)
) as v(sku, name, size, color, qty, unit_price, unit_cost)
left join public.stock_items si on si.sku = v.sku
where not exists (select 1 from public.sale_items existing where existing.sale_id = s.id);

with s as (
  insert into public.sales (code, sold_at, customer_name, phone, address, city, channel,
    delivery_method, delivery_fee, delivery_status, status, subtotal, total, paid, note)
  values ('S-0004', '2026-03-09', 'N', '87226982', 'BTB ផ្សារបឹងឈូក', 'Btb', 'booking', 'Delivery', 2.0, 'preparing', 'confirmed', 11.0, 13.0, 7.0, null)
  on conflict (code) do update set customer_name = excluded.customer_name
  returning id
)
insert into public.sale_items (sale_id, stock_item_id, name, size, color, qty, unit_price, unit_cost)
select s.id, si.id, v.name, v.size, v.color, v.qty, v.unit_price, v.unit_cost
from s
cross join (values
  ('SKU033', 'French-Style Lace Lingerie', '34', 'Black', 1, 5.5, 1.91),
  ('SKU043', 'Satin Lace ligerie', '34', 'Black', 1, 5.5, 2.0)
) as v(sku, name, size, color, qty, unit_price, unit_cost)
left join public.stock_items si on si.sku = v.sku
where not exists (select 1 from public.sale_items existing where existing.sale_id = s.id);

with s as (
  insert into public.sales (code, sold_at, customer_name, phone, address, city, channel,
    delivery_method, delivery_fee, delivery_status, status, subtotal, total, paid, note)
  values ('S-0005', '2026-03-09', 'meyy xiang', '969912598', 'Borey peng hout chea sophara', 'Phnom Penh', 'booking', 'Delivery', 1.5, 'preparing', 'confirmed', 8.5, 10.0, 5.0, null)
  on conflict (code) do update set customer_name = excluded.customer_name
  returning id
)
insert into public.sale_items (sale_id, stock_item_id, name, size, color, qty, unit_price, unit_cost)
select s.id, si.id, v.name, v.size, v.color, v.qty, v.unit_price, v.unit_cost
from s
cross join (values
  ('SKU046', 'ZARA tank top', 'Free size', 'Blue', 1, 3.0, 2.0),
  ('SKU043', 'Satin Lace ligerie', '34', 'Black', 1, 5.5, 2.0)
) as v(sku, name, size, color, qty, unit_price, unit_cost)
left join public.stock_items si on si.sku = v.sku
where not exists (select 1 from public.sale_items existing where existing.sale_id = s.id);

with s as (
  insert into public.sales (code, sold_at, customer_name, phone, address, city, channel,
    delivery_method, delivery_fee, delivery_status, status, subtotal, total, paid, note)
  values ('S-0006', '2026-03-09', 'Jhan jing', '977212399', 'ផ្សារឈូកមាស', 'Phnom Penh', 'booking', 'Delivery', 1.5, 'delivered', 'confirmed', 11.0, 12.5, 12.5, null)
  on conflict (code) do update set customer_name = excluded.customer_name
  returning id
)
insert into public.sale_items (sale_id, stock_item_id, name, size, color, qty, unit_price, unit_cost)
select s.id, si.id, v.name, v.size, v.color, v.qty, v.unit_price, v.unit_cost
from s
cross join (values
  ('SKU034', 'French-Style Lace Lingerie', '36', 'Black', 1, 5.5, 1.91),
  ('SKU037', 'Summer french satin', '36', 'Black', 1, 5.5, 2.17)
) as v(sku, name, size, color, qty, unit_price, unit_cost)
left join public.stock_items si on si.sku = v.sku
where not exists (select 1 from public.sale_items existing where existing.sale_id = s.id);

with s as (
  insert into public.sales (code, sold_at, customer_name, phone, address, city, channel,
    delivery_method, delivery_fee, delivery_status, status, subtotal, total, paid, note)
  values ('S-0007', '2026-03-09', 'Summer', '12729199', 'Peng hout berng snor', 'Phnom Penh', 'booking', 'Delivery', 1.5, 'preparing', 'confirmed', 8.0, 9.5, 4.75, null)
  on conflict (code) do update set customer_name = excluded.customer_name
  returning id
)
insert into public.sale_items (sale_id, stock_item_id, name, size, color, qty, unit_price, unit_cost)
select s.id, si.id, v.name, v.size, v.color, v.qty, v.unit_price, v.unit_cost
from s
cross join (values
  ('SKU042', 'Satin Lace ligerie', '32', 'Black', 1, 5.5, 2.0),
  (null, 'Underwar B&W', 'S', '', 2, 1.25, 0.0)
) as v(sku, name, size, color, qty, unit_price, unit_cost)
left join public.stock_items si on si.sku = v.sku
where not exists (select 1 from public.sale_items existing where existing.sale_id = s.id);

with s as (
  insert into public.sales (code, sold_at, customer_name, phone, address, city, channel,
    delivery_method, delivery_fee, delivery_status, status, subtotal, total, paid, note)
  values ('S-0008', '2026-03-09', 'Ka', '81455593', 'BTB', 'Btb', 'booking', 'Delivery', 2.0, 'preparing', 'confirmed', 8.5, 10.5, 5.25, null)
  on conflict (code) do update set customer_name = excluded.customer_name
  returning id
)
insert into public.sale_items (sale_id, stock_item_id, name, size, color, qty, unit_price, unit_cost)
select s.id, si.id, v.name, v.size, v.color, v.qty, v.unit_price, v.unit_cost
from s
cross join (values
  (null, 'ZARA TOP', 'Free size', '', 1, 3.0, 0.0),
  ('SKU036', 'Summer french satin', '34', 'Black', 1, 5.5, 2.17)
) as v(sku, name, size, color, qty, unit_price, unit_cost)
left join public.stock_items si on si.sku = v.sku
where not exists (select 1 from public.sale_items existing where existing.sale_id = s.id);

with s as (
  insert into public.sales (code, sold_at, customer_name, phone, address, city, channel,
    delivery_method, delivery_fee, delivery_status, status, subtotal, total, paid, note)
  values ('S-0009', '2026-04-09', 'Ching', '77365515', 'Terk tla', 'Phnom Penh', 'booking', 'Delivery', 1.5, 'preparing', 'confirmed', 10.5, 12.0, 6.0, null)
  on conflict (code) do update set customer_name = excluded.customer_name
  returning id
)
insert into public.sale_items (sale_id, stock_item_id, name, size, color, qty, unit_price, unit_cost)
select s.id, si.id, v.name, v.size, v.color, v.qty, v.unit_price, v.unit_cost
from s
cross join (values
  ('SKU038', 'Summer french satin', '32', 'White', 1, 5.5, 2.17),
  ('SKU005', 'Black French lace sexy', '32', 'Black', 1, 5.0, 1.84)
) as v(sku, name, size, color, qty, unit_price, unit_cost)
left join public.stock_items si on si.sku = v.sku
where not exists (select 1 from public.sale_items existing where existing.sale_id = s.id);

with s as (
  insert into public.sales (code, sold_at, customer_name, phone, address, city, channel,
    delivery_method, delivery_fee, delivery_status, status, subtotal, total, paid, note)
  values ('S-0010', '2026-04-09', 'July', '87865337', 'កំពង់ស្ពឺផ្សារត្រពាំងក្រឡឹង', 'Kampong Spuer', 'booking', 'Delivery', 2.0, 'preparing', 'confirmed', 9.0, 11.0, 5.75, null)
  on conflict (code) do update set customer_name = excluded.customer_name
  returning id
)
insert into public.sale_items (sale_id, stock_item_id, name, size, color, qty, unit_price, unit_cost)
select s.id, si.id, v.name, v.size, v.color, v.qty, v.unit_price, v.unit_cost
from s
cross join (values
  ('SKU042', 'Satin Lace ligerie', '32', 'Black', 1, 5.0, 2.0),
  ('SKU039', 'Blue tiffiny top bow', 'Free size', 'Blue', 1, 4.0, 2.25)
) as v(sku, name, size, color, qty, unit_price, unit_cost)
left join public.stock_items si on si.sku = v.sku
where not exists (select 1 from public.sale_items existing where existing.sale_id = s.id);

with s as (
  insert into public.sales (code, sold_at, customer_name, phone, address, city, channel,
    delivery_method, delivery_fee, delivery_status, status, subtotal, total, paid, note)
  values ('S-0011', '2026-04-09', 'Violet', '', 'TTP', 'Phnom Penh', 'booking', 'Delivery', 1.0, 'delivered', 'confirmed', 7.5, 8.5, 8.5, null)
  on conflict (code) do update set customer_name = excluded.customer_name
  returning id
)
insert into public.sale_items (sale_id, stock_item_id, name, size, color, qty, unit_price, unit_cost)
select s.id, si.id, v.name, v.size, v.color, v.qty, v.unit_price, v.unit_cost
from s
cross join (values
  (null, 'White top', 'Free size', '', 1, 3.5, 0.0),
  (null, 'Black jean', 'Free size', '', 1, 4.0, 0.0)
) as v(sku, name, size, color, qty, unit_price, unit_cost)
left join public.stock_items si on si.sku = v.sku
where not exists (select 1 from public.sale_items existing where existing.sale_id = s.id);

with s as (
  insert into public.sales (code, sold_at, customer_name, phone, address, city, channel,
    delivery_method, delivery_fee, delivery_status, status, subtotal, total, paid, note)
  values ('S-0012', '2026-04-09', 'Kim long', '67796076', 'KPS', 'Kompong Soam', 'booking', 'Delivery', 2.0, 'delivered', 'confirmed', 8.5, 10.5, 10.5, null)
  on conflict (code) do update set customer_name = excluded.customer_name
  returning id
)
insert into public.sale_items (sale_id, stock_item_id, name, size, color, qty, unit_price, unit_cost)
select s.id, si.id, v.name, v.size, v.color, v.qty, v.unit_price, v.unit_cost
from s
cross join (values
  (null, 'Bra', '38', '', 1, 5.0, 0.0),
  (null, 'Blue top', 'Free size', '', 1, 3.5, 0.0)
) as v(sku, name, size, color, qty, unit_price, unit_cost)
left join public.stock_items si on si.sku = v.sku
where not exists (select 1 from public.sale_items existing where existing.sale_id = s.id);

with s as (
  insert into public.sales (code, sold_at, customer_name, phone, address, city, channel,
    delivery_method, delivery_fee, delivery_status, status, subtotal, total, paid, note)
  values ('S-0013', '2026-04-09', 'Pichyy', '712379100', 'Sterng mean chey', 'Phnom Penh', 'booking', 'Delivery', 1.5, 'delivered', 'confirmed', 18.5, 20.0, 19.0, null)
  on conflict (code) do update set customer_name = excluded.customer_name
  returning id
)
insert into public.sale_items (sale_id, stock_item_id, name, size, color, qty, unit_price, unit_cost)
select s.id, si.id, v.name, v.size, v.color, v.qty, v.unit_price, v.unit_cost
from s
cross join (values
  ('SKU044', 'Satin Lace ligerie', '38', 'Black', 1, 5.5, 2.0),
  (null, 'Jean', 'L', '', 1, 9.0, 0.0),
  (null, 'ZARA top', 'Free size', '', 1, 4.0, 0.0)
) as v(sku, name, size, color, qty, unit_price, unit_cost)
left join public.stock_items si on si.sku = v.sku
where not exists (select 1 from public.sale_items existing where existing.sale_id = s.id);

with s as (
  insert into public.sales (code, sold_at, customer_name, phone, address, city, channel,
    delivery_method, delivery_fee, delivery_status, status, subtotal, total, paid, note)
  values ('S-0014', '2026-05-09', 'Walk-in customer', '974750704', '', '', 'booking', 'Delivery', 2.0, 'delivered', 'confirmed', 6.5, 8.5, 8.5, null)
  on conflict (code) do update set customer_name = excluded.customer_name
  returning id
)
insert into public.sale_items (sale_id, stock_item_id, name, size, color, qty, unit_price, unit_cost)
select s.id, si.id, v.name, v.size, v.color, v.qty, v.unit_price, v.unit_cost
from s
cross join (values
  (null, 'Underwar B&W', 'M', '', 2, 1.25, 0.0),
  (null, 'ZARA top', 'Free size', '', 1, 4.0, 0.0)
) as v(sku, name, size, color, qty, unit_price, unit_cost)
left join public.stock_items si on si.sku = v.sku
where not exists (select 1 from public.sale_items existing where existing.sale_id = s.id);

with s as (
  insert into public.sales (code, sold_at, customer_name, phone, address, city, channel,
    delivery_method, delivery_fee, delivery_status, status, subtotal, total, paid, note)
  values ('S-0015', '2026-05-09', 'Monypich', '99811356', 'Batambong', 'Btb', 'booking', 'Delivery', 2.0, 'delivered', 'confirmed', 7.5, 9.5, 9.5, null)
  on conflict (code) do update set customer_name = excluded.customer_name
  returning id
)
insert into public.sale_items (sale_id, stock_item_id, name, size, color, qty, unit_price, unit_cost)
select s.id, si.id, v.name, v.size, v.color, v.qty, v.unit_price, v.unit_cost
from s
cross join (values
  (null, 'ZARA top', 'Free size', '', 1, 4.0, 0.0),
  (null, 'Tank top', 'Free size', '', 1, 3.5, 0.0)
) as v(sku, name, size, color, qty, unit_price, unit_cost)
left join public.stock_items si on si.sku = v.sku
where not exists (select 1 from public.sale_items existing where existing.sale_id = s.id);

with s as (
  insert into public.sales (code, sold_at, customer_name, phone, address, city, channel,
    delivery_method, delivery_fee, delivery_status, status, subtotal, total, paid, note)
  values ('S-0016', '2026-05-09', 'Jkaa', '962549929', '', '', 'booking', 'Delivery', 1.5, 'preparing', 'confirmed', 9.5, 11.0, 5.5, null)
  on conflict (code) do update set customer_name = excluded.customer_name
  returning id
)
insert into public.sale_items (sale_id, stock_item_id, name, size, color, qty, unit_price, unit_cost)
select s.id, si.id, v.name, v.size, v.color, v.qty, v.unit_price, v.unit_cost
from s
cross join (values
  (null, 'Top wihte', 'Free size', '', 1, 4.0, 0.0),
  ('SKU043', 'Satin Lace ligerie', '34', 'Black', 1, 5.5, 2.0)
) as v(sku, name, size, color, qty, unit_price, unit_cost)
left join public.stock_items si on si.sku = v.sku
where not exists (select 1 from public.sale_items existing where existing.sale_id = s.id);

with s as (
  insert into public.sales (code, sold_at, customer_name, phone, address, city, channel,
    delivery_method, delivery_fee, delivery_status, status, subtotal, total, paid, note)
  values ('S-0017', '2026-05-09', 'Lee', '968109036', '', '', 'booking', 'Delivery', 2.0, 'preparing', 'confirmed', 10.25, 12.25, 12.25, null)
  on conflict (code) do update set customer_name = excluded.customer_name
  returning id
)
insert into public.sale_items (sale_id, stock_item_id, name, size, color, qty, unit_price, unit_cost)
select s.id, si.id, v.name, v.size, v.color, v.qty, v.unit_price, v.unit_cost
from s
cross join (values
  (null, 'Tank top white', 'Free size', '', 1, 3.5, 0.0),
  ('SKU041', 'Underwear', 'M', 'White', 1, 1.25, 0.83),
  (null, 'Bra', '38', '', 1, 5.5, 0.0)
) as v(sku, name, size, color, qty, unit_price, unit_cost)
left join public.stock_items si on si.sku = v.sku
where not exists (select 1 from public.sale_items existing where existing.sale_id = s.id);

with s as (
  insert into public.sales (code, sold_at, customer_name, phone, address, city, channel,
    delivery_method, delivery_fee, delivery_status, status, subtotal, total, paid, note)
  values ('S-0018', '2026-05-09', 'Ching houy', '965238499', '', '', 'booking', 'Delivery', 0.0, 'preparing', 'confirmed', 12.0, 12.0, 0.0, null)
  on conflict (code) do update set customer_name = excluded.customer_name
  returning id
)
insert into public.sale_items (sale_id, stock_item_id, name, size, color, qty, unit_price, unit_cost)
select s.id, si.id, v.name, v.size, v.color, v.qty, v.unit_price, v.unit_cost
from s
cross join (values
  (null, 'ZARA top black', 'Free size', '', 1, 3.0, 0.0),
  (null, 'bra', '36', '', 1, 5.5, 0.0),
  (null, 'blue top', 'Free size', '', 1, 3.5, 0.0)
) as v(sku, name, size, color, qty, unit_price, unit_cost)
left join public.stock_items si on si.sku = v.sku
where not exists (select 1 from public.sale_items existing where existing.sale_id = s.id);

with s as (
  insert into public.sales (code, sold_at, customer_name, phone, address, city, channel,
    delivery_method, delivery_fee, delivery_status, status, subtotal, total, paid, note)
  values ('S-0019', '2026-06-09', 'Gek', '964318774', '', '', 'booking', 'Delivery', 2.0, 'preparing', 'confirmed', 8.5, 10.5, 5.25, null)
  on conflict (code) do update set customer_name = excluded.customer_name
  returning id
)
insert into public.sale_items (sale_id, stock_item_id, name, size, color, qty, unit_price, unit_cost)
select s.id, si.id, v.name, v.size, v.color, v.qty, v.unit_price, v.unit_cost
from s
cross join (values
  (null, 'Tank top white', 'Free size', '', 1, 3.0, 0.0),
  ('SKU034', 'French-Style Lace Lingerie', '36', 'Black', 1, 5.5, 1.91)
) as v(sku, name, size, color, qty, unit_price, unit_cost)
left join public.stock_items si on si.sku = v.sku
where not exists (select 1 from public.sale_items existing where existing.sale_id = s.id);

-- ── cash ledger ──────────────────────────────────────────────
-- Guarded by `where not exists`: finance rows have no natural key, so this
-- is what keeps a second run from doubling the ledger.
insert into public.finance_entries (entry_date, kind, description, category, amount, method, source)
select v.entry_date::date, v.kind, v.description, v.category, v.amount::numeric, v.method, v.source
from (values
  ('2026-01-09', 'expense', 'Buy clothes from 1688', 'Inventory', 57.28, 'cash', 'import'),
  ('2026-01-09', 'expense', 'Buy Bra from 1688', 'Inventory', 10.55, 'cash', 'import'),
  ('2026-03-09', 'income', 'Customer buy Bra', 'Sales', 13.0, 'cash', 'import'),
  ('2026-03-09', 'income', 'Customer booking Bra', 'Sales', 9.0, 'cash', 'import'),
  ('2026-03-09', 'income', 'Customer booking Bra', 'Sales', 7.0, 'cash', 'import'),
  ('2026-03-09', 'expense', 'Buy bra from Loda', 'Inventory', 18.84, 'cash', 'import'),
  ('2026-03-09', 'income', 'Customer booking Bra', 'Sales', 5.0, 'cash', 'import'),
  ('2026-03-09', 'expense', 'Buy bra from loda', 'Inventory', 11.48, 'cash', 'import'),
  ('2026-03-09', 'income', 'Customer booking Bra', 'Sales', 5.25, 'cash', 'import'),
  ('2026-03-09', 'income', 'Customer booking Bra pay full', 'Sales', 12.5, 'cash', 'import'),
  ('2026-03-09', 'income', 'Customer booking Bra and under', 'Sales', 4.75, 'cash', 'import'),
  ('2026-04-09', 'income', 'Customer booking Bra', 'Sales', 6.0, 'cash', 'import'),
  ('2026-04-09', 'income', 'Customer buy clothes', 'Sales', 10.5, 'cash', 'import'),
  ('2026-04-09', 'income', 'Customer booking Bra andtop', 'Sales', 5.75, 'cash', 'import'),
  ('2026-04-09', 'income', 'Customer buy clothes', 'Sales', 8.5, 'cash', 'import'),
  ('2026-04-09', 'income', 'Customer buy clothes', 'Sales', 10.0, 'cash', 'import'),
  ('2026-04-09', 'expense', 'Buy clothes from ly', 'Inventory', 6.95, 'cash', 'import'),
  ('2026-04-09', 'expense', 'Buy bra from blue store', 'Inventory', 2.48, 'cash', 'import'),
  ('2026-04-09', 'expense', 'delivery to VET', 'Delivery', 1.49, 'cash', 'import'),
  ('2026-05-09', 'income', 'Customer buy clothes and under wear', 'Sales', 8.5, 'cash', 'import'),
  ('2026-05-09', 'expense', 'Buy bra from loda', 'Inventory', 7.11, 'cash', 'import'),
  ('2026-05-09', 'expense', 'buy Zara top', 'Inventory', 11.87, 'cash', 'import'),
  ('2026-05-09', 'income', 'Customer buy clothes', 'Sales', 9.5, 'cash', 'import'),
  ('2026-05-09', 'expense', 'Buy mini printer', 'Inventory', 18.0, 'cash', 'import'),
  ('2026-05-09', 'income', 'Customer booking clothes and bra', 'Sales', 5.5, 'cash', 'import'),
  ('2026-05-09', 'income', 'Customer buy clothes', 'Sales', 12.25, 'cash', 'import'),
  ('2026-06-09', 'income', 'Customer booking set bra', 'Sales', 5.25, 'cash', 'import'),
  ('2026-06-09', 'expense', 'Buy bra from 1688', 'Inventory', 20.55, 'cash', 'import'),
  ('2026-08-31', 'income', 'Customer booking bra and Jean Pay full', 'Sales', 16.0, 'cash', 'import')
) as v(entry_date, kind, description, category, amount, method, source)
where not exists (select 1 from public.finance_entries where source = 'import');

commit;

notify pgrst, 'reload schema';
