/**
 * Local (offline) backend for the POS.
 *
 * Used when Supabase is not configured — the whole back office runs from
 * localStorage, pre-seeded with the data imported from the shop's old
 * spreadsheet (`src/data/shop-seed.json`, generated by tools/import_excel.py).
 *
 * This keeps the POS usable on a laptop with no internet, and gives a working
 * demo before the Supabase project is connected. It is single-device storage,
 * so `exportBackup()` in store.ts is the safety net.
 */
import seed from "@/data/shop-seed.json";
import {
  round2,
  type FinanceEntry,
  type Sale,
  type SaleItem,
  type StockItem,
  type StockMovement,
} from "./types";

const STORAGE_KEY = "nichnich-pos-v1";
const isBrowser = typeof window !== "undefined";

export interface PosSnapshot {
  version: 1;
  stockItems: StockItem[];
  sales: Sale[];
  financeEntries: FinanceEntry[];
  movements: StockMovement[];
}

interface SeedStockItem {
  sku: string;
  name: string;
  category: string;
  size: string;
  color: string;
  cost: number;
  price: number;
  stockIn: number;
  sold: number;
}

interface SeedSaleItem {
  sku: string | null;
  name: string;
  size: string;
  color: string;
  qty: number;
  unitPrice: number;
  unitCost: number;
}

interface SeedSale {
  code: string;
  date: string;
  customerName: string;
  phone: string;
  address: string;
  city: string;
  channel: string;
  deliveryMethod: string;
  deliveryFee: number;
  deliveryStatus: string;
  status: string;
  subtotal: number;
  total: number;
  paid: number;
  note: string;
  items: SeedSaleItem[];
}

interface SeedFinanceEntry {
  date: string;
  kind: string;
  description: string;
  category: string;
  amount: number;
  method: string;
  source: string;
}

interface SeedFile {
  stockItems: SeedStockItem[];
  sales: SeedSale[];
  financeEntries: SeedFinanceEntry[];
}

export function newId(prefix: string): string {
  const random =
    typeof crypto !== "undefined" && "randomUUID" in crypto
      ? crypto.randomUUID().slice(0, 8)
      : Math.random().toString(36).slice(2, 10);
  return `${prefix}_${Date.now().toString(36)}${random}`;
}

/** Build the initial snapshot from the imported spreadsheet data. */
export function buildSeedSnapshot(): PosSnapshot {
  const file = seed as unknown as SeedFile;
  const now = new Date().toISOString();

  const stockItems: StockItem[] = file.stockItems.map((row) => ({
    id: `st_${row.sku}`,
    sku: row.sku,
    name: row.name,
    category: row.category,
    size: row.size,
    color: row.color,
    cost: row.cost,
    price: row.price,
    stockIn: row.stockIn,
    sold: row.sold,
    // Alert only when an item is actually sold out. The shop stocks 1–3 units
    // per SKU, so a higher threshold would flag almost everything.
    lowStockAt: 0,
    archived: false,
    note: "",
    updatedAt: now,
  }));

  const bySku = new Map(stockItems.map((item) => [item.sku, item]));

  const sales: Sale[] = file.sales.map((row) => ({
    id: `sl_${row.code}`,
    code: row.code,
    soldAt: row.date,
    customerName: row.customerName,
    phone: row.phone,
    address: row.address,
    city: row.city,
    channel: (row.channel as Sale["channel"]) ?? "booking",
    deliveryMethod: row.deliveryMethod,
    deliveryFee: row.deliveryFee,
    deliveryStatus: (row.deliveryStatus as Sale["deliveryStatus"]) ?? "preparing",
    status: (row.status as Sale["status"]) ?? "confirmed",
    subtotal: row.subtotal,
    discount: 0,
    total: row.total,
    paid: row.paid,
    paymentMethod: "cash",
    note: row.note ?? "",
    createdAt: `${row.date}T09:00:00.000Z`,
    items: row.items.map((line, index): SaleItem => {
      const match = line.sku ? bySku.get(line.sku) : undefined;
      return {
        id: `sli_${row.code}_${index}`,
        stockItemId: match?.id ?? null,
        name: line.name,
        size: line.size,
        color: line.color,
        qty: line.qty,
        unitPrice: line.unitPrice,
        unitCost: line.unitCost,
      };
    }),
  }));

  const financeEntries: FinanceEntry[] = file.financeEntries.map((row, index) => ({
    id: `fe_${index}`,
    entryDate: row.date,
    kind: row.kind === "expense" ? "expense" : "income",
    description: row.description,
    category: row.category,
    amount: row.amount,
    method: row.method || "cash",
    source: "import",
    saleId: null,
    createdAt: `${row.date}T09:00:00.000Z`,
  }));

  return { version: 1, stockItems, sales, financeEntries, movements: [] };
}

let memory: PosSnapshot | null = null;

export function readSnapshot(): PosSnapshot {
  if (!isBrowser) {
    memory ??= buildSeedSnapshot();
    return memory;
  }
  const stored = window.localStorage.getItem(STORAGE_KEY);
  if (!stored) {
    const fresh = buildSeedSnapshot();
    writeSnapshot(fresh);
    return fresh;
  }
  try {
    const parsed = JSON.parse(stored) as PosSnapshot;
    return {
      version: 1,
      stockItems: parsed.stockItems ?? [],
      sales: parsed.sales ?? [],
      financeEntries: parsed.financeEntries ?? [],
      movements: parsed.movements ?? [],
    };
  } catch {
    const fresh = buildSeedSnapshot();
    writeSnapshot(fresh);
    return fresh;
  }
}

export function writeSnapshot(snapshot: PosSnapshot): void {
  if (!isBrowser) {
    memory = snapshot;
    return;
  }
  window.localStorage.setItem(STORAGE_KEY, JSON.stringify(snapshot));
}

/** Read → mutate → persist, returning whatever the mutation produced. */
export function mutate<T>(fn: (snapshot: PosSnapshot) => T): T {
  const snapshot = readSnapshot();
  const result = fn(snapshot);
  writeSnapshot(snapshot);
  return result;
}

export function replaceSnapshot(snapshot: PosSnapshot): void {
  writeSnapshot(snapshot);
}

export function resetToSeed(): PosSnapshot {
  const fresh = buildSeedSnapshot();
  writeSnapshot(fresh);
  return fresh;
}

/** Next SKU in the SKU001, SKU002... sequence used by the shop. */
export function nextSku(existing: StockItem[]): string {
  let highest = 0;
  for (const item of existing) {
    const match = /^SKU(\d+)$/i.exec(item.sku.trim());
    if (match) highest = Math.max(highest, Number(match[1]));
  }
  return `SKU${String(highest + 1).padStart(3, "0")}`;
}

/** Next sale code in the S-0001, S-0002... sequence. */
export function nextSaleCode(existing: Sale[]): string {
  let highest = 0;
  for (const sale of existing) {
    const match = /^S-(\d+)$/.exec(sale.code.trim());
    if (match) highest = Math.max(highest, Number(match[1]));
  }
  return `S-${String(highest + 1).padStart(4, "0")}`;
}

export function recalcSaleTotals(sale: Sale): Sale {
  const subtotal = round2(sale.items.reduce((sum, item) => sum + item.qty * item.unitPrice, 0));
  return {
    ...sale,
    subtotal,
    total: round2(Math.max(subtotal - sale.discount + sale.deliveryFee, 0)),
  };
}
